# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: OUTPUT_DIR

# Dataset arguments
dataset_id_or_path: mila-ai4h/AIMS.au
class_of_interest: Approval # Or Signature, C2 (operations) etc.

eval_mode: false
project_name: PROJECT_NAME
use_judge: true

# Lora Arguments
# No LoRA is used here

# Training arguments
max_steps: 7000
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-6 # 1.0e-6 as in the deepseek math paper 5-e7 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
lr_scheduler_type: cosine
warmup_ratio: 0.1
# GRPO specific parameters
beta: 0.04 # 0.04 as in the deepseek math paper 0.001 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
max_prompt_length: 4000
max_completion_length: 1000
num_generations: 4
use_vllm: true
vllm_device: cuda:2
vllm_gpu_memory_utilization: 0.7

# Logging arguments
logging_strategy: steps
logging_steps: 1
report_to:
  - comet_ml
  - wandb
save_strategy: "steps"
save_steps: 500
seed: 42

# Hugging Face Hub
push_to_hub:
  false
  # hub_model_id: llama-3-1-8b-math-orca-qlora-10k-ep1 # if not defined same as output_dir
hub_strategy: every_save

# Judge arguments
provider_type: "local" # Options: local, api
judge_model_name: "nuojohnchen/JudgeLRM-7B" # Options:Qwen/Qwen2.5-7B-Instruct, nuojohnchen/JudgeLRM-7B
# criteria: "approval" # Options: approval, signature,
judge_model_device: cuda:1
api_url: http://localhost:8009
